<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>The Brickz</title>
	<link rel="stylesheet" href="<?= BASE_URL ?>/Application/Resources/static/style.css">
</head>
<body>
	<div class="title">
		<h1>The Brickz</h1>
	</div>
	<div class="container">
		<form action="game.html" method="post">
			<input type="text" placeholder="Nickname" name="name">
			<select name="bricks" id="bricks">
				<option value="3">3 Bricks</option>
				<option value="4">4 Bricks</option>
				<option value="5">5 Bricks</option>
			</select>
			<input type="submit" value="Start Game">
		</form>
	</div>
</body>
</html>